import logging

from slime.utils.mask_utils import MultiTurnLossMaskGenerator
from slime.utils.processing_utils import build_processor_kwargs, load_processor, load_tokenizer

__all__ = ["generate_rollout"]

logger = logging.getLogger(__name__)

_PROCESSOR_PROMPT_KEYS = {"input_ids", "attention_mask"}


TOKENIZER = None
PROCESSOR = None
MASK_GENERATOR = None
SAMPLE_PRINTED = False


def generate_rollout(args, rollout_id, data_buffer, evaluation=False):
    """An example to implement the generate_rollout function for an rule based rm rollout generation.

    Args:
        args: the whole args
        rollout_id: int, the id of the rollout, used for deterministic data generation
        data_buffer: the data buffer to store the generated samples
        evaluation: bool, whether the rollout is for evaluation or not

    Returns:
        list[Sample]: a list of samples generated by the rollout
    """
    assert not evaluation
    assert args.rollout_global_dataset

    global TOKENIZER, PROCESSOR, MASK_GENERATOR, SAMPLE_PRINTED
    if TOKENIZER is None:
        TOKENIZER = load_tokenizer(args.hf_checkpoint, trust_remote_code=True)

    if PROCESSOR is None:
        PROCESSOR = load_processor(args.hf_checkpoint, trust_remote_code=True)

    if MASK_GENERATOR is None:
        MASK_GENERATOR = MultiTurnLossMaskGenerator(TOKENIZER, tokenizer_type=args.loss_mask_type)

    samples = data_buffer.get_samples(args.rollout_batch_size)

    for i, sample in enumerate(samples):
        (sample,) = sample
        messages = sample.prompt
        tools = sample.metadata.get("tools", None)

        raw_multimodal_inputs = sample.multimodal_inputs or {}
        has_multimodal_inputs = PROCESSOR is not None and any(
            value is not None for value in raw_multimodal_inputs.values()
        )
        if has_multimodal_inputs:
            template_kwargs = dict(getattr(args, "apply_chat_template_kwargs", None) or {})
            template_kwargs["add_generation_prompt"] = False
            rendered = PROCESSOR.apply_chat_template(
                messages,
                tools=tools,
                tokenize=False,
                **template_kwargs,
            )
            processor_output = PROCESSOR(
                text=rendered,
                **build_processor_kwargs(raw_multimodal_inputs),
            )
            token_ids = list(processor_output["input_ids"][0])
            sample.multimodal_train_inputs = {
                key: value
                for key, value in processor_output.items()
                if key not in _PROCESSOR_PROMPT_KEYS
            } or None
            token_ids, loss_mask = MASK_GENERATOR.get_loss_mask_with_multimodal_alignment(
                messages,
                token_ids,
                tools=tools,
            )
        else:
            token_ids, loss_mask = MASK_GENERATOR.get_loss_mask(messages, tools=tools)
        if len(token_ids) != len(loss_mask):
            raise ValueError(
                f"SFT rollout produced mismatched token_ids/loss_mask lengths: {len(token_ids)=}, {len(loss_mask)=}"
            )

        response_length = MASK_GENERATOR.get_response_lengths([loss_mask])[0]

        sample.tokens = token_ids
        sample.response_length = response_length
        sample.reward = 0
        sample.loss_mask = loss_mask[-response_length:]

        if i == 0 and not SAMPLE_PRINTED:
            logger.info(
                f"sft_rollout::generate_rollout example data: {sample=} (raw){messages=} (raw){token_ids=} (raw){loss_mask=} {response_length=}"
            )
            SAMPLE_PRINTED = True

    return samples
